apiVersion: v1
kind: Service
metadata:
  name: multicurrency-ars
  labels:
    app: multicurrency-ars
    service: multicurrency-ars
spec:
  ports:
  - port: 80
    name: multicurrency-ars-tue
    protocol: TCP 
    targetPort: 8080
  selector:
    app: multicurrency-ars-tue